server:
  env_name: ${APP_ENV:prod}
  port: ${PORT:8080}

llm:
  mode: ${LLM_MODE:-vllm}

embedding:
  mode: ${EMBEDDING_MODE:-text_embeddings_inference}

vectorstore:
  database: ${VECTOR_STORE:-weaviate}

vllm:
  vllm_endpoint: ${VLLM_ENDPOINT:-http://103.145.79.20:6017/v1/completions}
  llm_model: Viet-Mistral/Vistral-7B-Chat
  prompt_style: default
  temperature: 1
  max_tokens: 1024

text_embeddings_inference:
  text_embeddings_inference_endpoint: ${TEXT_EMBEDDINGS_INFERENCE_ENDPOINT:-http://localhost:8081}
  timeout: 60

weaviate:
  weaviate_endpoint: ${WEAVIATE_ENDPOINT:-http://localhost:9091}
  index_name: Law07032024

rag:
  similarity_top_k: 50
  #This value controls how many "top" documents the RAG returns to use in the context.
  #similarity_value: 0.45
  #This value is disabled by default.  If you enable this settings, the RAG will only use articles that meet a certain percentage score.
  
  custom_retriever:
    enabled: true
    version: v2

  rerank:
    enabled: false
    top_n: 3
    mode: model_api

translation:
  enabled: true
  mode: triton
  model: nllb-200-distilled-600M
  src_lang: vie_Latn
  tag_lang: eng_Latn
    
translation_tokenizer:
  pretrained_model_name_or_path: ${TOKENIZER_PRETRAINED:-facebook/nllb-200-distilled-600M}
  truncation: true
  max_length: 30
  padding: max_length

translation_triton_server:
  triton_server_endpoint: ${TRITON_SERVER_ENDPOINT:-localhost:8001}
  triton_model_name: ${TRITON_MODEL_NAME:-nllb-200-distilled-600M-fp16}

model_api_rerank:
  model_api_endpoint: http://localhost:8084/rerank
  
ui:
  enabled: true
  path: /
  default_chat_system_prompt: >
    Bạn là một trợ lí Tiếng Việt nhiệt tình và trung thực. 
    Hãy luôn trả lời một cách hữu ích nhất có thể, đồng thời giữ an toàn.
    Câu trả lời của bạn không nên chứa bất kỳ nội dung gây hại, phân biệt chủng tộc, phân biệt giới tính, độc hại, nguy hiểm hoặc bất hợp pháp nào. 
    Hãy đảm bảo rằng các câu trả lời của bạn không có thiên kiến xã hội và mang tính tích cực.Nếu một câu hỏi không có ý nghĩa hoặc không hợp lý về mặt thông tin, hãy giải thích tại sao thay vì trả lời một điều gì đó không chính xác. 
    Nếu bạn không biết câu trả lời cho một câu hỏi, hãy trẳ lời là bạn không biết và vui lòng không chia sẻ thông tin sai lệch
  delete_file_button_enabled: true
  delete_all_files_button_enabled: true