# https://www.digitalocean.com/community/tutorials/how-to-use-ansible-to-install-and-set-up-docker-on-ubuntu-22-04
- name: Deploy grafana
  hosts: servers # Which host to apply, you can replace by `servers`, or by `servers_1, servers_2` for multiple groups
  become: yes # To run commands as a superuser (e.g., sudo)
  vars:
    # grafana
    grafana_container_image: grafana/grafana:9.0.5
    grafana_container_name: grafana

  tasks:
    - name: Pull the jenkins docker image
      community.docker.docker_image:
        name: "{{ jenkins_container_image }}"
        source: pull

    - name: Pull the grafana docker image
      community.docker.docker_image:
        name: "{{ grafana_container_image }}"
        source: pull

    - name: Run grafana container
      community.docker.docker_container:
        name: "{{ default_container_name }}"
        image: "{{ default_container_image }}"
        state: started
        privileged: true
        user: root
        volumes:
          - jenkins_home:/var/jenkins_home
          - /var/run/docker.sock:/var/run/docker.sock
        ports:
          - 8081:8080
          - 50000:50000
        detach: yes
      
    - name: Copy grafana config from local
      ansible.builtin.copy:
        src: /home/duongntd/Documents/DATN/private-gpt/perf
        dest: /home/duongntd2