namespace: rag

configmap:
  name: rag-config

  labels:
    appName: rag-config

deployment:
  name: rag-deploy

  image:
    name: duong05102002/legal-rag
    version: v1.1
    imagePullPolicy: IfNotPresent

  container: 
    name: rag
    portName: rag
    portNumber: 8080

  labels:
    appName: rag

  replicaCount: 1

  resources:
    requests:
      cpu: 2
      memory: 3Gi
    limits:
      cpu: 2.5
      memory: 4Gi

service:
  name: rag-svc

  type: LoadBalancer

  httpPort:
    enable: true

    port: 80

    nodePort: 32001

    targetPort: 8080

ingress:
  name: rag-ing
  host: 34.81.253.13.nip.io

hpa:
  name: rag-hpa

  minReplicas: 1

  maxReplicas: 4

  cpu:
    enable: true
    targetCPUUtilizationPercentage: 80

  memory:
    enable: true
    targetMemoryUtilizationPercentage: 70

configmap:
  name: rag-configmap
  data:
    PROFILES: prod
    RAG_WORKERS: "1"
    LLM_MODE: nvidia_nim
    EMBEDDING_MODE: text_embeddings_inference
    VECTOR_STORE: weaviate
    VLLM_ENDPOINT: http://103.145.79.20:6017/generate
    LLM_MODEL: Viet-Mistral/Vistral-7B-Chat
    TEXT_EMBEDDINGS_INFERENCE_ENDPOINT: http://35.194.199.238
    WEAVIATE_ENDPOINT: http://104.199.221.145
    SIMILARITY_TOP_K: "5"
    VLLM_MAX_TOKENS: "1024"

secret:
  name: rag-secret