namespace: rag

configmap:
  name: rag-config

  labels:
    appName: rag-config

deployment:
  name: rag-deploy

  image:
    name: duong05102002/legal-rag
    version: v0.0.3
    imagePullPolicy: IfNotPresent

  container: 
    name: rag
    portName: rag
    portNumber: 8080

  labels:
    appName: rag

  replicaCount: 1

  resources:
    requests:
      cpu: 0.5
      memory: 0.5Gi
    limits:
      cpu: 1
      memory: 1Gi

service:
  name: rag-svc

  type: LoadBalancer

  httpPort:
    enable: true

    port: 80

    nodePort: 32001

    targetPort: 8080

hpa:
  name: rag-hpa
  minReplicas: 1
  maxReplicas: 2
  cpu:
    enable: true
    targetCPUUtilizationPercentage: 80
  memory:
    enable: true
    targetMemoryUtilizationPercentage: 70
