apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector: 
    app: {{ .Values.deployment.labels.appName }}
  type: {{ .Values.service.type }}  
  ports:
    - port: {{ .Values.service.httpPort.port }}
      protocol: TCP
      targetPort: {{ .Values.service.httpPort.targetPort }}
  type: {{ .Values.service.type }}