apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
  namespace: {{ .Values.namespace }}
spec:
  selector: 
    app: {{ .Values.deployment.labels.appName }}
  type: {{ .Values.service.type }}  
#   ports:
# {{- if .Values.service.httpPort.enable }}
#   - port: {{ .Values.service.httpPort.port }}
#     targetPort: {{ .Values.service.httpPort.targetPort }}
#     protocol: TCP
#     name: http
#   {{- if eq .Values.service.type "NodePort" }}
#     nodePort: {{ .Values.service.httpPort.nodePort }}
#   {{- end }}
# {{- end }}
  ports:
    - port: {{ .Values.service.httpPort.port }}
      protocol: TCP
      targetPort: {{ .Values.service.httpPort.targetPort }}
  type: {{ .Values.service.type }}